name = "UncertainADCS"
uuid = "130c74cf-01d7-43c5-bd0c-db96c2b5ddd6"
version = "0.1.0"
authors = ["Ottavia Personeni <otpers03@stanford.edu>", "Emma Nicolai <enicolai@stanford.edu", "Zeb Barry <zbarry@stanford.edu>"]

[deps]
BasicPOMCP = "d721219e-3fc6-5570-a8ef-e5402f47c49e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FIB = "13b007ba-0ca8-5af2-9adf-bc6a6301e25a"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
ParticleFilters = "c8b314e2-9260-5cf8-ae76-3be7461ca6d0"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PointBasedValueIteration = "835c131e-675f-4498-8e2c-c054c75556e1"
QMDP = "3aa3ecc9-5a5d-57c8-8188-3e47bd8068d2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SARSOP = "cef570c6-3a94-5604-96b7-1a5e143043f2"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BasicPOMCP = "0.3.12"
Distributions = "0.25.122"
FIB = "0.4.5"
POMDPTools = "1.1.0"
POMDPs = "1.0.0"
Parameters = "0.12.3"
Plots = "1.41.1"
PointBasedValueIteration = "0.2.4"
QMDP = "0.1.8"
Random = "1.11.0"
SARSOP = "0.6.0"
Statistics = "1.11.1"
